version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch-mwlr
    volumes:
      - elasticsearch-mwlr:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
  db:
    image: postgres
    container_name: postgres-mwlr
    restart: always
    environment:
      POSTGRES_PASSWORD: "hamburger subfloor backhand fervor"
    volumes:
      - postgres-mwlr:/var/lib/postgresql/data
  geonetwork:
    build: .
    ports:
      - 8086:8080
    environment:
      ES_HOST: elasticsearch-mwlr
      DATA_DIR: /var/lib/geonetwork/data
      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_NAME: gn
      GEONETWORK_DB_USERNAME: postgres
      GEONETWORK_DB_PASSWORD: "hamburger subfloor backhand fervor"
      GEONETWORK_DB_HOST: postgres-mwlr
      GEONETWORK_DB_PORT: 5432
    volumes:
      - gn-data-mwlr:/var/lib/geonetwork/data
volumes:
  elasticsearch-mwlr:
  gn-data-mwlr:
  postgres-mwlr:
